services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_DATABASE_URL=mysql+pymysql://root:1234qwer@db:3306/ziptie
    depends_on:
      - db

  db:
    image: mysql:9.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234qwer
      MYSQL_DATABASE: ziptie
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql